"""Core data model shared across all Snapmap modules.

These dataclasses are the contract between the scanner, prober, screenshotter
and report generator. Keep field names stable — the HTML report and the JSON
export are generated directly from ``endpoint_to_dict``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

DEFAULT_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0 Safari/537.36 Snapmap"
)


@dataclass
class Service:
    """A single open TCP service as reported by nmap."""

    port: int
    protocol: str = "tcp"
    state: str = "open"
    name: str = ""
    product: str = ""
    version: str = ""
    extrainfo: str = ""
    tunnel: str = ""

    @property
    def banner(self) -> str:
        return " ".join(p for p in (self.product, self.version, self.extrainfo) if p)


@dataclass
class Host:
    """A host discovered by nmap with its open services."""

    address: str
    address_type: str = "ipv4"
    hostnames: list[str] = field(default_factory=list)
    services: list[Service] = field(default_factory=list)


@dataclass
class CredCandidate:
    """A default-credential pair proposed for a fingerprinted product."""

    product: str
    username: str
    password: str


@dataclass
class Issue:
    """A finding attached to an endpoint.

    ``source`` is ``auto`` for issues generated by Snapmap and ``manual`` for
    issues the analyst adds inside the HTML report (those live only client-side).
    """

    id: str
    title: str
    severity: str  # one of: critical, high, medium, low, info
    detail: str = ""
    source: str = "auto"


@dataclass
class Endpoint:
    """A single web endpoint (scheme + host + port) and everything we learn about it."""

    url: str
    scheme: str
    ip: str
    port: int
    host: str = ""  # hostname or ip used to build the url

    # nmap-derived service info
    nmap_service: str = ""
    nmap_product: str = ""
    nmap_version: str = ""

    # probe results
    probed: bool = False
    status: Optional[int] = None
    reason: str = ""
    title: str = ""
    server: str = ""
    content_type: str = ""
    content_length: Optional[int] = None
    final_url: str = ""
    redirects: list[str] = field(default_factory=list)
    response_headers: dict[str, str] = field(default_factory=dict)
    technologies: list[str] = field(default_factory=list)
    security_headers: dict[str, bool] = field(default_factory=dict)
    tls: Optional[dict[str, Any]] = None
    favicon_hash: Optional[int] = None

    # derived
    cred_candidates: list[CredCandidate] = field(default_factory=list)
    issues: list[Issue] = field(default_factory=list)
    interest: int = 0

    # visual
    screenshot: str = ""  # base64-encoded PNG, no data-uri prefix
    error: str = ""

    @property
    def alive(self) -> bool:
        return self.status is not None

    @property
    def subnet(self) -> str:
        """The /24 the endpoint IP belongs to (best-effort, ipv4)."""
        parts = self.ip.split(".")
        if len(parts) == 4:
            return ".".join(parts[:3]) + ".0/24"
        return self.ip


@dataclass
class Options:
    """All tunable knobs, populated from the CLI and passed down the pipeline."""

    # nmap
    ports: str = "web"
    rate: int = 5000
    timing: int = 4
    no_ping: bool = False
    service_detection: bool = True
    sudo: bool = False
    nmap_extra: list[str] = field(default_factory=list)

    # target derivation
    include_hostnames: bool = True

    # probing
    concurrency: int = 20
    timeout: float = 15.0
    follow_redirects: bool = True
    proxy: Optional[str] = None
    headers: dict[str, str] = field(default_factory=dict)
    user_agent: str = DEFAULT_UA
    verify_tls: bool = False
    do_favicon: bool = True
    do_tls: bool = True

    # screenshots
    screenshots: bool = True
    full_page: bool = False
    screenshot_delay: int = 0  # ms
    screenshot_timeout: int = 20000  # ms
    screenshot_concurrency: int = 5

    # report
    project: Optional[str] = None  # if set, outputs go into a folder named after it
    group_by: str = "host"  # host | subnet | none
    report_all: bool = False  # include non-responsive endpoints in the HTML report
    output: str = "snapmap_report.html"
    json_out: Optional[str] = None
    csv_out: Optional[str] = None
